server:
  port: 8888
  password: 123456
  prefix: 183.
  logFile: server.log

client:
  logFile: client.log
  namesilo:
    api-key: 8d58a6f8ca27b0bb1cd482fd7
    targetHost: cloud
    domain: shit-code.com
  server:
    port: 50888
    host: ip.shit-code.com
    password: 202007182319Cd*